<template>
  <div>
    <main>
      <section class="space-y-4 p-6">
        <div
          class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 auto-rows-fr"
        >
          <div
            v-for="module in settingsStore.settings.chordDisplay"
            :key="`chord-display/${module.id}`"
          >
            <ModuleCard
              :to="`/chords/${module.id}`"
              :settings-to="`/settings/chords/${module.id}`"
              :title="$t('nav.chordDisplayWithId', { moduleId: module.id })"
              :description="$t('home.moduleDescriptions.chordDisplay')"
              icon="mdi-piano"
            />
          </div>
          <div>
            <ModuleCard
              to="/chord-dictionary"
              settings-to="/settings/chord-dictionary"
              :title="$t('nav.chordDictionary')"
              :description="$t('home.moduleDescriptions.chordDictionary')"
              icon="mdi-book-open-page-variant"
            />
          </div>
          <div>
            <ModuleCard
              to="/waterfall-piano"
              settings-to="/settings/waterfall-piano"
              :title="$t('nav.WaterfallPiano')"
              :description="$t('home.moduleDescriptions.WaterfallPiano')"
              icon="mdi-piano"
            />
          </div>
          <div>
            <ModuleCard
              to="/sampler"
              :title="$t('nav.Sampler')"
              :description="$t('home.moduleDescriptions.Sampler')"
              icon="mdi-music-note"
            />
          </div>
          <div>
            <ModuleCard
              to="/chord-quiz"
              :title="$t('nav.chordQuiz')"
              :description="$t('home.moduleDescriptions.chordQuiz')"
              icon="mdi-help-circle"
            />
          </div>
          <div>
            <ModuleCard
              to="/tuner"
              :title="$t('nav.tuner')"
              :description="$t('home.moduleDescriptions.tuner')"
              icon="mdi-tune-vertical"
            />
          </div>
          <div>
            <ModuleCard
              to="/score-scroll"
              :title="$t('nav.scoreScroll')"
              :description="$t('home.moduleDescriptions.scoreScroll')"
              icon="mdi-music-note-eighth"
            />
          </div>
          <div>
            <ModuleCard
              to="/score-3d"
              settings-to="/settings/score-3d"
              :title="$t('nav.score3d')"
              :description="$t('home.moduleDescriptions.score3d')"
              icon="mdi-cube-outline"
            />
          </div>
          <div>
            <ModuleCard
              to="/circle-of-fifths"
              :title="$t('nav.circleOfFifths')"
              :description="$t('home.moduleDescriptions.circleOfFifths')"
              icon="mdi-circle-of-fifths"
            />
          </div>
          <div>
            <ModuleCard
              to="/metronome"
              :title="$t('nav.metronome')"
              :description="$t('home.moduleDescriptions.metronome')"
              icon="mdi-metronome"
            />
          </div>
          <div>
            <ModuleCard
              to="/chord-chart"
              :title="$t('nav.chordChart')"
              :description="$t('home.moduleDescriptions.chordChart')"
              icon="mdi-lead-sheet"
            />
          </div>
          <div>
            <ModuleCard
              to="/vst"
              :title="$t('nav.vst')"
              :description="$t('home.moduleDescriptions.vst')"
              icon="mdi-puzzle"
            />
          </div>
          <div>
            <ModuleCard
              to="/settings/routing"
              settings-to="/settings/routing"
              :title="$t('nav.routing')"
              :description="$t('home.moduleDescriptions.routing')"
              icon="mdi-swap-horizontal"
            />
          </div>
          <div>
            <ModuleCard
              to="/settings/debug"
              settings-to="/settings/debug"
              :title="$t('nav.debugger')"
              :description="$t('home.moduleDescriptions.debugger')"
              icon="mdi-bug"
            />
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<script setup lang="ts">
import { useSettingsStore } from "@/stores";
import ModuleCard from "./components/ModuleCard.vue";

const settingsStore = useSettingsStore();
</script>
